### ISSUE TITLE
missing TKDESTEP.lib when building IFC_BuildingEnvExtractor

### ISSUE THREAD

**Issue by StevenSchuerstedt** [jaspervdv/IFC_BuildingEnvExtractor#4]
Hey there,
Im trying to build the project and run into a couple of issues. First I tried to build it with ifcopenshell v0.8, but I got errors because things like `ifcgeom_schema_agnostic` are missing. I guess these where refactored/moved into different modules. Using ifcopenshell v0.7 works in that regard. I suggest to edit the readme of this repo and specifiy the correct version of ifcopenshell. 
Next I tried with opencascade v7.9.3, again there is an error with things like `mesh->Nodes()`. I downgraded my opencascade version to 7.4 but no the linker tells me the TKDESTEP.lib is missing. These lib exists with opencascade 7.9.3 but not with 7.4. 
What is the correct version of opencascade to use for this project?

**Comment by jaspervdv** [comment]
Hey!

Good call, the code is indeed developed on IfcOpenShell v0.7. I will add it to the readme. The local build I have utilizes the open cascade version that is supplied with IfcOpenShell. In my case this is 7.5.3.

**Comment by StevenSchuerstedt** [comment]
okay thank you. I build opencascade 7.5.3 as it comes with ifcopenshell but I still do not see a TKDESTEP.lib
This part of the cmakelists.txt is causing problems for me:
```
if(OCC_VERSION_STRING VERSION_LESS 7.8.0)
    list(APPEND OPENCASCADE_LIBRARY_NAMES  TKIGES TKSTEPBase TKSTEPAttr TKSTEP209 TKSTEP)
else(OCC_VERSION_STRING VERSION_LESS 7.8.0)
    list(APPEND OPENCASCADE_LIBRARY_NAMES TKDESTEP TKDEIGES)
endif(OCC_VERSION_STRING VERSION_LESS 7.8.0)
```
shouldnt the second statement be something like `VERSION_GREATER`?
Also I dont see how the code should work with an occ version greater 7.8, as there are alot of changes. 

I manually added the `list(APPEND OPENCASCADE_LIBRARY_NAMES  TKIGES TKSTEPBase TKSTEPAttr TKSTEP209 TKSTEP)` . This seems to be correct. I need to rebuild my ifcopenshell with opencascade 7.5.3 and then I will see if it builds. Can tell you tomorrow.

**Comment by jaspervdv** [comment]
Ah yeah that if statement was a bit of an oversight. Thanks for the catch. The Cmake files have been a bit of a hacky process. 

The distinction between 7.8 and newer was just made because some libs were merged and changed between opencascade versions... somewhere around there, not if it works with the code. It would indeed be best to add some safeguards.

**Comment by StevenSchuerstedt** [comment]
compiling works now, but I do get alot of linker errors. I build on windows 11, with Visual Studio 2022-x64 in release mode. There is a problem with CJT and some unresolved external symbols in the ifcopenshell libs (see code snippet below). Am I missing some libraries in my linker input? From OpenCascade? Maybe you can copy your linker input or check if there is something missing?


**Linker Input**:
C:\local\boost_1_82_0\lib64-msvc-14.3\libboost_filesystem-vc143-mt-x64-1_82.lib
bcrypt.lib
ws2_32.lib
C:\Users\no9964\Documents\CJT\Build\Release\CJT.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc2x3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_add1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_add2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_rc1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_rc2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_rc3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_rc4.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcGeom_ifc4x3_tc1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\IfcParse.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc2x3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_add1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_add2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_rc1.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_rc2.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_rc3.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_rc4.lib
C:\IfcOpenShell\_installed-vs2022-x64\lib\Serializers_ifc4x3_tc1.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKernel.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKMath.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKBRep.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKGeomBase.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKGeomAlgo.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKG3d.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKG2d.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKShHealing.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKTopAlgo.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKMesh.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKPrim.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKBool.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKBO.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKFillet.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKXSBase.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKOffset.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKHLR.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKBin.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKV3d.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKIGES.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKSTEPBase.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKSTEPAttr.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKSTEP209.lib
C:\IfcOpenShell\_deps-vs2022-x64-installed\opencascade-7.5.3\win64\lib\TKSTEP.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib

**Linker-Errors:**
1>------ Build started: Project: Ifc_Envelope_Extractor, Configuration: Release x64 ------
1>CJT.lib(CJToKernel.obj) : error LNK2038: mismatch detected for 'boost_log_abi': value 'v2_mt_nt6' doesn't match value 'v2s_mt_nt6' in main.obj
1>   Creating library C:/Users/no9964/Documents/IFC_BuildingEnvExtractor/build/Release/Ifc_Envelope_Extractor.lib and object C:/Users/no9964/Documents/IFC_BuildingEnvExtractor/build/Release/Ifc_Envelope_Extractor.exp
1>IfcGeom.lib(IfcGeomRepresentation.obj) : error LNK2019: unresolved external symbol "public: void __cdecl Poly_Triangle::Get(int &,int &,int &)const " (?Get@Poly_Triangle@@QEBAXAEAH00@Z) referenced in function "public: __cdecl IfcGeom::Representation::Triangulation::Triangulation(class IfcGeom::Representation::BRep const &)" (??0Triangulation@Representation@IfcGeom@@QEAA@AEBVBRep@12@@Z)
1>IfcGeom.lib(wire_utils.obj) : error LNK2001: unresolved external symbol "public: void __cdecl Poly_Triangle::Get(int &,int &,int &)const " (?Get@Poly_Triangle@@QEBAXAEAH00@Z)
1>IfcGeom.lib(IfcGeomRepresentation.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl BRepTools::Write(class TopoDS_Shape const &,class std::basic_ostream<char,struct std::char_traits<char> > &,class opencascade::handle<class Message_ProgressIndicator> const &)" (?Write@BRepTools@@SAXAEBVTopoDS_Shape@@AEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z) referenced in function "public: __cdecl IfcGeom::Representation::Serialization::Serialization(class IfcGeom::Representation::BRep const &)" (??0Serialization@Representation@IfcGeom@@QEAA@AEBVBRep@12@@Z)
1>IfcGeom.lib(IfcGeomRepresentation.obj) : error LNK2019: unresolved external symbol "public: class gp_Ax3 const & __cdecl Geom_ElementarySurface::Position(void)const " (?Position@Geom_ElementarySurface@@QEBAAEBVgp_Ax3@@XZ) referenced in function "void __cdecl `anonymous namespace'::surface_area_along_direction(double,class TopoDS_Shape const &,class gp_Ax3 const &,double &,double &,double &)" (?surface_area_along_direction@?A0x86a5a514@@YAXNAEBVTopoDS_Shape@@AEBVgp_Ax3@@AEAN22@Z)
1>IfcGeom.lib(base_utils.obj) : error LNK2001: unresolved external symbol "public: class gp_Ax3 const & __cdecl Geom_ElementarySurface::Position(void)const " (?Position@Geom_ElementarySurface@@QEBAAEBVgp_Ax3@@XZ)
1>IfcGeom.lib(boolean_utils.obj) : error LNK2001: unresolved external symbol "public: class gp_Ax3 const & __cdecl Geom_ElementarySurface::Position(void)const " (?Position@Geom_ElementarySurface@@QEBAAEBVgp_Ax3@@XZ)
1>IfcGeom.lib(base_utils.obj) : error LNK2019: unresolved external symbol "public: void __cdecl BRepBuilderAPI_Sewing::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@BRepBuilderAPI_Sewing@@QEAAXAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z) referenced in function "bool __cdecl IfcGeom::util::create_solid_from_faces(class NCollection_List<class TopoDS_Shape> const &,class TopoDS_Shape &,double,bool)" (?create_solid_from_faces@util@IfcGeom@@YA_NAEBV?$NCollection_List@VTopoDS_Shape@@@@AEAVTopoDS_Shape@@N_N@Z)
1>IfcGeom.lib(layerset.obj) : error LNK2001: unresolved external symbol "public: void __cdecl BRepBuilderAPI_Sewing::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@BRepBuilderAPI_Sewing@@QEAAXAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom.lib(wire_utils.obj) : error LNK2001: unresolved external symbol "public: void __cdecl BRepBuilderAPI_Sewing::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@BRepBuilderAPI_Sewing@@QEAAXAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcFace.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom.lib(shape_item.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom.lib(boolean_utils.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom.lib(layerset.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcAnnotationFillArea.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcArbitraryProfileDefWithVoids.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcRectangleHollowProfileDef.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcCircleHollowProfileDef.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_rc4.lib(IfcCircleHollowProfileDef.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_rc4.lib(IfcFace.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcCurveBoundedPlane.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_tc1.lib(IfcSweptDiskSolid.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
1>IfcGeom_ifc4x3_rc4.lib(IfcSweptDiskSolid.obj) : error LNK2001: unresolved external symbol "public: bool __cdecl ShapeFix_Shape::Perform(class opencascade::handle<class Message_ProgressIndicator> const &)" (?Perform@ShapeFix_Shape@@QEAA_NAEBV?$handle@VMessage_ProgressIndicator@@@opencascade@@@Z)
etc

**Comment by jaspervdv** [comment]
Interesting...

So it seems that "...IfcOpenshell\_installed-vs2019-x64\lib\libsvgfill.lib" is missing, But this does actually not influence the working of the code.

The CJT issue seems to be related to a mismatch between static linking boost and dynamic linking it. 

I hope that the OCCT issues are also somehow related to CJT. Maybe it has been utilizing a different version of OpenCascade which is causing some issues?

**Comment by StevenSchuerstedt** [comment]
I added BOOST_LOG_DYN_LINK in the preprocessor and built everything in debug mode, now it works. I used the exact same OCC for CJT, ifcopenshell and env-extractor. 
But now it crashes when I try to convert a ifc building, which works with the shipped binaries. It crashes in nlohmann::json helperFunctions::getAttributes.

**Comment by jaspervdv** [comment]
great that it works now!

can you tell me something more about the crash? The getAttributes function has changed compared to the binaries. So probably the IFC file you try to process has some minor quirk that i did not anticipate. If you can share the file that is also fine, so i can check myself.

**Comment by StevenSchuerstedt** [comment]
Im very happy I got it running :) sure I used this file. 

[AC26-FZK-Haus.zip](https://github.com/user-attachments/files/25839581/AC26-FZK-Haus.zip)

**Comment by jaspervdv** [comment]
Interesting, I hit no issues when processing it myself. Could you give me some more info about the crash?

**Comment by StevenSchuerstedt** [comment]
okay I was missing some recent updates...I pulled the latest changes from git and now everything works fine! 
thank you. I will close the issue now
